# -*- coding: utf-8 -*-
"""despliegueataquealcora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DP41b608P3o4g-ZxQoG71cKT9OojBXy

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo

import pickle
filename = 'modelo-class (1).pkl'
modelo,labelencoder, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

#Cargamos los datos futuros
data = pd.read_excel("ataque_corazon.xlsx", sheet_name=1)
data.head()

!pip install streamlit

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
import pandas as pd

st.title('Predicción de riesgo de ataque al corazón')

age = st.slider('Edad', min_value=18, max_value=100, value=50, step=1)
hypertension = st.selectbox('Hipertensión', ['No', 'Yes'])
heart_disease = st.selectbox('Enfermedad cardíaca', ['No', 'Yes'])
ever_married = st.selectbox('Casado/a alguna vez', ['Yes', 'No'])
avg_glucose_level = st.number_input('Nivel promedio de glucosa', min_value=50.0, max_value=300.0, value=100.0, step=0.01)
smoking_status = st.selectbox('Estado de fumador', ["'never smoked'", "smokes", "Unknown", "'formerly smoked'"])


#Dataframe
datos = [[age, hypertension, heart_disease, ever_married, avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level', 'smoking_status']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['age','hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level',	'smoking_status'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['Age', 'avg_glucose_level']]= min_max_scaler.transform(data_preparada[['Age', 'avg_glucose_level']])
data_preparada.head()

"""## Predicciones"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)



data['Prediccion']=Y_pred
data.head()

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 7%")